sonar.projectKey=dvntone_wifisentry
sonar.organization=dvntone
sonar.projectName=wifisentry
sonar.projectVersion=1.2.7c

# Path to sources
sonar.sources=.
sonar.exclusions=**/node_modules/**, **/.next/**, **/dist/**, **/android-native/.gradle/**

# Language specific settings
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.kotlin.binaries=android-native/app/build/tmp/kotlin-classes/debug
